version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - produtrue_network

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "5173:80"
    depends_on:
      - frontend
    networks:
      - produtrue_network

networks:
  produtrue_network:
    driver: bridge