version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Mapeia a porta 80 do contêiner para a porta 3000 do host

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Mapeia a porta 80 do contêiner para a porta 80 do host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
